In [1]:
# Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv(r'E:\AI\LibrariesForAI\Supervised_Learning\1_Simple_Linear_Regression\homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
x_df = df.drop(['price'],axis=1)
x_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [4]:
y_df = df['price']
y_df

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [5]:
lr = LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [6]:
# m
lr.coef_

array([135.78767123])

In [7]:
# b
lr.intercept_

180616.43835616432

#### Pickle File

In [8]:
import pickle

In [9]:
with open("lr_model",'wb') as file:
    pickle.dump(lr,file)

In [10]:
with open("lr_model",'rb') as file:
    mp = pickle.load(file)

In [11]:
mp.coef_

array([135.78767123])

In [12]:
mp.intercept_

180616.43835616432

#### save trained model using joblib

In [13]:
import joblib

In [15]:
joblib.dump(lr,"model_joblib")

['model_joblib']

In [17]:
mp = joblib.load('model_joblib')

In [18]:
mp.coef_

array([135.78767123])

In [19]:
mp.intercept_

180616.43835616432