In [1]:
# install python package - Numpy

In [2]:
# install python package - Numpy
# pip install numpy

In [1]:
import numpy as np

In [2]:
myList=[1,2,3,4,5]

In [3]:
print(myList)

[1, 2, 3, 4, 5]


In [4]:
type(myList)

list

In [5]:
# dir(np)

In [6]:
# help(np)

In [7]:
arr = np.array(myList)

In [8]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
# shape of the array
arr.shape

(5,)

In [10]:
arr.size

5

In [11]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])


In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.shape

(3, 5)

In [14]:
arr.size

15

In [15]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [16]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [17]:
# numpy array indexing
my_list1=[1,2,3,4,5]
arr = np.array(my_list1)

In [18]:
print(arr[0])

1


In [19]:
print(arr[1])

2


In [20]:
print("Thired element is ",arr[2],"and Fourth element is ",arr[3])


Thired element is  3 and Fourth element is  4


In [21]:
# Access 2D array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr = np.array([my_lst1,my_lst2,my_lst3])

In [22]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [23]:
arr[0,2]

3

In [24]:
arr[2,4]

9

In [25]:
valArr = np.array([[1,2,3],[4,5,6]])
# print the variable
# get shape
# get size
# index: first row First element
# index second row third element


In [26]:
# print the variable
print("Printing the variable : ",valArr)

Printing the variable :  [[1 2 3]
 [4 5 6]]


In [27]:
# get shape
print("Printing the shape",valArr.shape)

Printing the shape (2, 3)


In [28]:
# get size
print("Printing the size",valArr.size)

Printing the size 6


In [29]:
# index: first row First element
print("Indexing first row first element",valArr[0,0])

Indexing first row first element 1


In [30]:
# index second row third element
print("Indexing second row second element",valArr[1,2])

Indexing second row second element 6


In [31]:
# create  a 5*5 array
newArr= np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])
print("Printing the variable",newArr)

Printing the variable [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]]


In [32]:
print("Printing the shape",newArr.shape)

Printing the shape (5, 5)


In [33]:
print("Printing the size",newArr.size)

Printing the size 25


In [34]:
print("Indexing second row second element",newArr[1,2])

Indexing second row second element 8


In [35]:
#negative indexing
valArr = np.array([[1,2,3],[4,5,6]])
print(valArr)



[[1 2 3]
 [4 5 6]]


In [36]:
valArr[1,-2]

5

In [37]:
valArr[0,2]

3

In [38]:
# Numpy array slicing
mylist=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(mylist)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [40]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [42]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [43]:
arr[-1]

10

In [44]:
arr[-3:-1]

array([8, 9])

In [45]:
arr[-3:]

array([ 8,  9, 10])

In [46]:
arr[-3:-2]

array([8])

In [47]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
arr[::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# step
arr[::2]

array([1, 3, 5, 7, 9])

In [50]:
arr[1::2]

array([ 2,  4,  6,  8, 10])

In [51]:
arr[1:3:3]

array([2])

In [52]:
arr[1::3]

array([2, 5, 8])

In [53]:
# 2D slicing
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr = np.array([my_lst1,my_lst2,my_lst3])

print(arr.shape)

(3, 5)


In [54]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [55]:
arr[:,:2]

array([[1, 2],
       [2, 3],
       [9, 7]])

In [56]:
arr[1:,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [57]:
arr[1:,1:4]

array([[3, 4, 5],
       [7, 6, 8]])

In [58]:
# Arange function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [62]:
arr[1:,1:3]

array([[3, 4],
       [7, 6]])

In [63]:
arr[1:3,3:]

array([[5, 6],
       [8, 9]])

In [64]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [65]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [66]:
# Linspace
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [67]:
arr=np.array([1,2,3,4]) # Let numpy choose the datatype
arr1=np.array([1.2,2.5])
print(arr1.dtype)
print(arr.dtype)

float64
int32


In [68]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [69]:
arr=np.array(['apple','banana','cherry','bananacherry'])
print(arr.dtype)

<U12


In [70]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [71]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [72]:
arr=np.array([1,2,3,4,5],dtype=np.int64)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [73]:
arr=np.array([1.2,2.5,3.7,4.9,5.5],dtype=np.float32)
print(arr)
print(arr.dtype)

[1.2 2.5 3.7 4.9 5.5]
float32


In [74]:
# Array Math
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print("****")
print(y)

[[1 2]
 [3 4]]
****
[[5 6]
 [7 8]]


In [75]:
x+y

array([[ 6,  8],
       [10, 12]])

In [76]:
x-y

array([[-4, -4],
       [-4, -4]])

In [77]:
x*y

array([[ 5, 12],
       [21, 32]])

In [78]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [79]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [80]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [81]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [82]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [83]:
np.square(x,y)

array([[ 1,  4],
       [ 9, 16]])

In [84]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [85]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8],[9,10]])

In [86]:
# shape error bcoz m*n and n*p-> m*p
np.add(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
np.exp(x)

In [ ]:
np.log(x)

In [87]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [88]:
np.tan(x)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [89]:
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [90]:
# Floor,Ceil,Round
x=np.array([[1.5,2.6],[3.1,4.9]],dtype=np.float64)

In [91]:
print(x)

[[1.5 2.6]
 [3.1 4.9]]


In [92]:
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [93]:
np.ceil(x)

array([[2., 3.],
       [4., 5.]])

In [94]:
np.round(x)

array([[2., 3.],
       [3., 5.]])

In [95]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
z=np.array([[9,10],[11,12]])

In [96]:
x*y*z

array([[ 45, 120],
       [231, 384]])

In [97]:
# in numpy consider only first two variable, so we give x and y in a single variable
np.multiply(x,y,z)

array([[ 5, 12],
       [21, 32]])

In [98]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [99]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
# 0 indicates column
# 1 indicates row
np.sum(x,axis=0) # row wise sum

array([12, 15, 18])

In [101]:
np.sum(x,axis=1)# column wise sum

array([ 6, 15, 24])

In [143]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
# transpos is coverting row as column and column as row
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [102]:
# Numpy array copy vs view
arr=np.array([1,2,3,4,5])
x=arr

In [103]:
print(arr)

[1 2 3 4 5]


In [104]:
print(x)

[1 2 3 4 5]


In [105]:
arr[0]=100
print(arr)

[100   2   3   4   5]


In [106]:
print(x)

[100   2   3   4   5]


In [109]:
x[1]=200

In [110]:
print(x)

[100 200   3   4   5]


In [111]:
# Numpy array copy
# if we give copy(), updation only affecting the arr object not x, when updating x it will effect
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [112]:
print(arr)

[1 2 3 4 5]


In [113]:
print(x)

[1 2 3 4 5]


In [114]:
arr[0]=100

In [115]:
print(arr)

[100   2   3   4   5]


In [116]:
x[1]=50

In [117]:
print(x)

[ 1 50  3  4  5]


In [126]:
# Numpy array reshaping
arr=np.arange(1,13)
print(arr)
arr.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12]


(12,)

In [120]:
arr.reshape(4,3)  # converting 1D to 2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [129]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [124]:
arr_new = arr.reshape(3,4)
print(arr_new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [122]:
arr.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [125]:
# Flattening the array
# converting 2D to 1D
arr_new.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [130]:
# Iterating Array
arr = np.arange(1,7).reshape
print(arr)


[[1 2]
 [3 4]
 [5 6]]


In [131]:
for i in arr:
    print(i)

[1 2]
[3 4]
[5 6]


In [132]:
arr = np.arange(1,7)
print(arr)

[1 2 3 4 5 6]


In [133]:
for i in arr:
    print(i)

1
2
3
4
5
6


In [134]:
# Joining numpy array in 1D
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


In [136]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [138]:
# Joining numpy array in 2D
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [139]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [140]:
arr1

array([[1, 2],
       [3, 4]])

In [141]:
arr2

array([[5, 6],
       [7, 8]])